name: Module Update
description: Module Update
labels:
  - Module-Update
title: '[Update]: your-module-name v0.0.0'
body:
  - type: markdown
    attributes:
      value: |
        Fill out this form to request the version of your module included in the beta builds to be updated. Or if your module is new and not yet included that can be done here too.

        You do not need to create the tag in your repository, but you do need to update the version number in the `package.json` file.

        If there is another issue open here for your module, then please add a comment there instead.
  
  - type: input
    attributes:
      label: Module name (eg generic-osc)
    validations:
      required: true

  - type: input
    attributes:
      label: New version number
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: I have updated the version number in the package.json for my module, and there is not already a git tag with that version
      options:
        - label: The version in package.json matches the above
          required: true

  - type: textarea
    attributes:
      label: Summary of the changes
      description: Please provide a brief summary of what changed in this new version of your module
    validations:
      required: false
      
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
